# Usar uma imagem base do Python
FROM python

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o arquivo print_hash.py para o diretório de trabalho
COPY print_hash.py .

# Executar o script print_hash.py quando o contêiner for iniciado
CMD ["python", "print_hash.py"]
